### ISSUE TITLE
Constant errors after 11.0

### ISSUE THREAD

**Issue by venorme** [lqnrd/Mushroom-Network-HUD#2]
This WA is huge timesaver.
After prepatch it started giving out constant errors any time you are in mushroom area.
Also only few sign are shown
Error message from bugsack:

1313x [string "return function() if not aura_env.f then"]:53: attempt to call global 'GetSpellInfo' (a nil value)
[string "return function() if not aura_env.f then"]:53: in function `UpdatePortalNames'
[string "return function() if not aura_env.f then"]:63: in function <[string "return function() if not aura_env.f then"]:61>

Locals:
self = TheRingFrame {
 p = FontString {
 }
 ids = <table> {
 }
 aura_env = <table> {
 }
 size = 1000
}
(for state) = <table> {
 325660 = <table> {
 }
 325619 = <table> {
 }
 325616 = <table> {
 }
 325620 = <table> {
 }
 355204 = <table> {
 }
 325617 = <table> {
 }
 325621 = <table> {
 }
 325614 = <table> {
 }
 325629 = <table> {
 }
 325618 = <table> {
 }
 325607 = <table> {
 }
 308436 = <table> {
 }
 325602 = <table> {
 }
}
(for control) = 355204
i = 355204
v = <table> {
 1 = 0.551300
 2 = 0.529300
 3 = true
}
poiInfo = nil
name = nil
(*temporary) = nil
(*temporary) = 355204
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"
t = <table> {
 325660 = <table> {
 }
 325619 = <table> {
 }
 325616 = <table> {
 }
 325620 = <table> {
 }
 355204 = <table> {
 }
 325617 = <table> {
 }
 325621 = <table> {
 }
 325614 = <table> {
 }
 325629 = <table> {
 }
 325618 = <table> {
 }
 325607 = <table> {
 }
 308436 = <table> {
 }
 325602 = <table> {
 }
}
f = TheRingFrame {
 p = FontString {
 }
 ids = <table> {
 }
 aura_env = <table> {
 }
 size = 1000
}
It`s way outside my abilities to fix.
If you ever have time for it - mind taking a look?

**Comment by lqnrd** [comment]
Thanks for the report! This should be fixed now: https://wago.io/swtNbFkqF
